#define WIFI_SSID "SEU_WIFI"
#define WIFI_PASSWORD "SUA_SENHA"

#define FIREBASE_API_KEY "SUA_API_KEY"
#define FIREBASE_DB_HOST "SEU_DATABASE.firebaseio.com"

#define DEVICE_EMAIL "USUARIO_DO_ESP32"
#define DEVICE_PASSWORD "SENHA_DO_ESP32"

#define DEVICE_SECRET "SEGREDO_DO_DISPOSITIVO"

#define APPS_SCRIPT_URL "URL_DO_GOOGLE_APPS_SCRIPT"
