import { initializeApp } from "https://www.gstatic.com/firebasejs/12.17.0/firebase-app.js";
import { getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut } from "https://www.gstatic.com/firebasejs/12.17.0/firebase-auth.js";
import { getDatabase, ref, set, get, push, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.17.0/firebase-database.js";
import { firebaseConfig, loginDomain, sheetsEndpoint } from "./firebase-config.js";

// Os arquivos recebidos possuem um espaço no início do nome; ele faz parte do caminho.
const pastaImagens="Imagens Bebidas/ ";
const catalogo={
  "ÁGUA":[["ÁGUA NATURAL","agua.jpeg"],["ÁGUA COM GÁS","agua com gas.jpeg"]],
  "CERVEJAS":[["SPATEN","cerveja-puro-malte-spaten-lt-269ml-1.jpg"],["STELLA ARTOIS","stella artois lata.jpg"],["PETRA ORIGEM","Cerveja-Puro-Malte-Petra-Origem-Lata-269ml.jpg"],["CORONA","corona.jpg"],["ORIGINAL GARRAFA","original-garrafa.jpg"],["BLUE MOON","cerveja-blue-moon-garrafa-355ml-1.jpg"],["ITAIPAVA","itaipava.jpg"],["AMSTEL","amstel.jpg"],["AMSTEL LAGER","cerveja-amstel-lager-lata-269ml-1.jpg"],["HEINEKEN GARRAFA","heineken-garrafa.jpeg"],["HEINEKEN LATA","heineken-lata.jpg"],["HEINEKEN ZERO GARRAFA","cerveja-heineken-zero-garrafa-330ml-1.jpg"],["HEINEKEN ZERO LATA","cerveja-heineken-zero-lata-269ml-1.jpg"],["BUDWEISER","cerveja-budweiser-american-lager-330ml-long-neck-1-2.jpg"],["SKOL","cerveja-skol-pilsen-lata-350ml-1.jpg"],["EISENBAHN PILSEN","cerveja-eisenbahn-pilsen-long-neck-355ml-1.jpg"],["SPATEN 600 ML","cerveja-spaten-one-way-600-ml-1.jpg"],["STELLA PURE GOLD","cerveja-stella-artois-pure-gold-330ml-1.jpg"],["ANTARCTICA","antarctica.jpeg"],["ORIGINAL LATA","original-lata.jpg"],["SUBZERO","subzero-lata.jpg"]],
  "SUCOS":[["SUCO PRATS LARANJA","suco prats laranja.jpg"],["DEL VALLE LARANJA","dellvale laranja.jpg"],["KAPO UVA","refresco-de-uva-del-valle-kapo-200ml-1.jpg"],["GATORADE TANGERINA","isotonico-gatorade-tangerina-garrafa-500ml-1.jpg"],["GATORADE MORANGO","isotonico-gatorade-morango-com-maracuja-500ml-garrafa-1.jpg"]],
  "REFRIGERANTES E OUTROS":[["COCA-COLA PET 200 ML","refrigerante-coca-cola-original-pet-200-ml-1.jpg"],["COCA-COLA 600 ML","coca-cola-600ml-1.jpg"],["COCA-COLA LATA","coca-cola-lata-350-ml-1.jpg"],["COCA-COLA 2 L","refrigerante-coca-cola-garrafa-2-l-1.jpg"],["COCA-COLA ZERO 2 L","cocazero 2litro.jpg"],["COCA-COLA ZERO LATA","cocazero-lata.jpg"],["FANTA LARANJA","fanta-laranja-220ml-1.jpg"],["GUARANÁ ANTARCTICA","refrigerante-guarana-antarctica-350ml-1.jpg"],["SPRITE","sprite.jpg"],["PEPSI","pepsi.jpg"],["SCHWEPPES CITRUS","refrigerante-schweppes-citrus-350ml-1.jpg"],["BEATS SENSES","drink-pronto-beats-senses-269ml-lata-1.jpg"],["RED BULL","redbull.jpeg"],["MONSTER ENERGY","energetico-monster-energy-lata-473ml-1.jpg"]]
};
const ordemCategorias=["ÁGUA","REFRIGERANTES E OUTROS","CERVEJAS","SUCOS"];
const produtos=Object.fromEntries(Object.values(catalogo).flat().map(([nome,imagem])=>[nome,{nome,imagem:pastaImagens+imagem.replace(/\.(jpg|jpeg)$/i,".png")}]))
const $=s=>document.querySelector(s);const telas=document.querySelectorAll(".tela");
const erroLogin=$("#erro-login"),erroCadastro=$("#erro-cadastro"),carrinhoModal=$("#carrinho"),listaCarrinho=$("#lista-carrinho"),botaoCarrinho=$("#botao-concluir"),resumoCarrinho=$("#resumo-carrinho"),obrigado=$("#obrigado"),barraCarrinho=$(".carrinho-barra");
const demoLocal=["localhost","127.0.0.1"].includes(location.hostname);
let app,auth,db,usuarioAtual=null,perfilAtual=null,carrinho={},retornoLogin=null;
$("#cad-senha").minLength=6;
["#cad-nome","#cad-usuario","#cad-telefone","#cad-cpf","#cad-senha"].forEach(seletor=>$(seletor).placeholder="");

function normalizarUsuario(valor){const u=valor.trim().toLowerCase();if(!/^[a-z0-9._-]{3,24}$/.test(u))throw new Error("USE DE 3 A 24 CARACTERES: LETRAS, NÚMEROS, PONTO, HÍFEN OU _.");return u;}
function emailInterno(usuario){return `${normalizarUsuario(usuario)}@${loginDomain}`;}
function mostrarTela(id){telas.forEach(t=>t.classList.toggle("ativa",t.id===id));}
function mensagemErro(erro){const mapa={"auth/invalid-credential":"USUÁRIO OU SENHA INCORRETOS.","auth/user-not-found":"USUÁRIO OU SENHA INCORRETOS.","auth/wrong-password":"USUÁRIO OU SENHA INCORRETOS.","auth/email-already-in-use":"ESTE NOME DE USUÁRIO JÁ EXISTE.","auth/weak-password":"A SENHA PRECISA TER AO MENOS 6 CARACTERES.","auth/network-request-failed":"VERIFIQUE SUA CONEXÃO COM A INTERNET."};return mapa[erro.code]||erro.message||"NÃO FOI POSSÍVEL CONCLUIR A OPERAÇÃO.";}
async function carregarPerfil(uid){const s=await get(ref(db,`users/${uid}`));if(!s.exists())throw new Error("CADASTRO NÃO ENCONTRADO.");return s.val();}
function mascaraNumeros(input,maximo){input.value=input.value.replace(/\D/g,"").slice(0,maximo);}
function mascaraCpf(){const digitos=$("#cad-cpf").value.replace(/\D/g,"").slice(0,11);$("#cad-cpf").value=digitos.replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d)/,"$1.$2").replace(/(\d{3})(\d{1,2})$/, "$1-$2");}
function cpfValido(cpf){cpf=cpf.replace(/\D/g,"");if(!/^\d{11}$/.test(cpf)||/^(\d)\1+$/.test(cpf))return false;let soma=0;for(let i=0;i<9;i++)soma+=+cpf[i]*(10-i);let d=11-(soma%11);if(d>=10)d=0;if(d!==+cpf[9])return false;soma=0;for(let i=0;i<10;i++)soma+=+cpf[i]*(11-i);d=11-(soma%11);return d>=10?+cpf[10]===0:d===+cpf[10];}

function exibirBebidas(){const caixa=$("#lista-bebidas");caixa.innerHTML=ordemCategorias.map(categoria=>[categoria,catalogo[categoria]]).map(([categoria,itens])=>`<section class="categoria"><h2>${categoria}</h2><div class="produtos">${itens.map(([nome])=>{const p=produtos[nome];return `<button class="produto" type="button" data-bebida="${nome}"><img class="produto-imagem" src="${encodeURI(p.imagem)}" alt="${nome}"><span class="produto-corpo"><span class="produto-nome">${nome}</span><span class="produto-add">+</span></span></button>`;}).join("")}</div></section>`).join("");carrinho={};atualizarCarrinho();mostrarTela("tela-bebidas");}
function totalItens(){return Object.values(carrinho).reduce((a,b)=>a+b,0);}function adicionar(nome){carrinho[nome]=(carrinho[nome]||0)+1;atualizarInterface();atualizarCarrinho();}function remover(nome){if(!carrinho[nome])return;if(--carrinho[nome]<=0)delete carrinho[nome];atualizarInterface();atualizarCarrinho();}function excluir(nome){delete carrinho[nome];atualizarInterface();atualizarCarrinho();}
function atualizarInterface(){document.querySelectorAll(".produto").forEach(b=>{const nome=b.dataset.bebida,q=carrinho[nome]||0,add=b.querySelector(".produto-add");b.classList.toggle("selecionada",q>0);add.innerHTML=q?`<span class="quantidade"><button type="button" data-minus="${nome}">−</button><span>${q}</span><button type="button" data-plus="${nome}">+</button></span>`:"+";});}
function atualizarCarrinho(){const total=totalItens();barraCarrinho.classList.toggle("tem-itens",total>0);resumoCarrinho.textContent=total?`${total} ITEN${total>1?"S":""} NO CARRINHO`:"CARRINHO VAZIO";botaoCarrinho.disabled=!total;listaCarrinho.innerHTML=total?Object.entries(carrinho).map(([nome,q])=>`<div class="item-carrinho"><img src="${encodeURI(produtos[nome].imagem)}" alt=""><strong>${nome}</strong><span class="quantidade"><button type="button" data-cart-minus="${nome}">−</button><span>${q}</span><button type="button" data-cart-plus="${nome}">+</button></span><button class="remover-item" type="button" data-remove="${nome}">REMOVER</button></div>`).join(""):`<div class="carrinho-vazio">NENHUMA BEBIDA ADICIONADA.</div>`;}
function abrirCarrinho(){atualizarCarrinho();carrinhoModal.classList.add("visivel");carrinhoModal.setAttribute("aria-hidden","false");}function fecharCarrinho(){carrinhoModal.classList.remove("visivel");carrinhoModal.setAttribute("aria-hidden","true");}
async function retornarAoLogin(){clearTimeout(retornoLogin);carrinho={};obrigado.classList.remove("visivel");fecharCarrinho();$("#confirmar-carrinho").disabled=false;if(auth&&!demoLocal)await signOut(auth);usuarioAtual=null;perfilAtual=null;mostrarTela("tela-login");}
function mostrarObrigado(){let segundos=5;const mensagem=obrigado.querySelector(".obrigado-conteudo p"),orientacao=obrigado.querySelectorAll(".obrigado-conteudo p")[1];mensagem.textContent="SUA ESCOLHA FOI REGISTRADA. A GELADEIRA SERÁ ABERTA EM INSTANTES.";orientacao.textContent="USE O BOTÃO × NO CANTO SUPERIOR PARA FECHAR ESTA TELA.";$("#contador").textContent=segundos;obrigado.classList.add("visivel");obrigado.focus();const intervalo=setInterval(()=>{$("#contador").textContent=--segundos;if(segundos<=0)clearInterval(intervalo);},1000);retornoLogin=setTimeout(()=>{mensagem.textContent="GELADEIRA ABERTA. RETIRE SUAS BEBIDAS E FECHE A PORTA AO TERMINAR.";$("#contador").textContent="✓";},5000);}
async function registrarPedidoNaPlanilha(orderId,items){
  const idToken=await usuarioAtual.getIdToken();
  const dados={orderId,uid:usuarioAtual.uid,idToken,fullName:perfilAtual.fullName,items};
  // Apps Script responde por redirecionamento; no-cors permite o POST simples
  // sem expor o token em URL nem depender da resposta do ESP32.
  await fetch(sheetsEndpoint,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=UTF-8"},body:JSON.stringify(dados)});
}

$("#form-login").addEventListener("submit",async e=>{e.preventDefault();erroLogin.textContent="";const usuario=$("#usuario").value,senha=$("#senha").value;if(demoLocal&&usuario.trim().toLowerCase()==="admin"&&senha==="ada26@"){usuarioAtual={uid:"demo-admin"};perfilAtual={username:"admin",fullName:"ADMIN"};$("#form-login").reset();exibirBebidas();return;}try{const cred=await signInWithEmailAndPassword(auth,emailInterno(usuario),senha);usuarioAtual=cred.user;perfilAtual=await carregarPerfil(usuarioAtual.uid);$("#form-login").reset();exibirBebidas();}catch(err){erroLogin.textContent=mensagemErro(err);}});
$("#abrir-cadastro").addEventListener("click",()=>{erroCadastro.textContent="";mostrarTela("tela-cadastro");});$("#voltar-login").addEventListener("click",()=>mostrarTela("tela-login"));
$("#cad-telefone").addEventListener("input",e=>mascaraNumeros(e.target,11));$("#cad-cpf").addEventListener("input",mascaraCpf);
$("#form-cadastro").addEventListener("submit",async e=>{e.preventDefault();erroCadastro.textContent="";try{const nome=$("#cad-nome").value.trim(),usuario=normalizarUsuario($("#cad-usuario").value),telefone=$("#cad-telefone").value.replace(/\D/g,""),cpf=$("#cad-cpf").value.replace(/\D/g,""),senha=$("#cad-senha").value;if(nome.length<3)throw new Error("INFORME O NOME COMPLETO.");if(telefone.length<10||telefone.length>11)throw new Error("INFORME O CELULAR COM DDD.");if(!cpfValido(cpf))throw new Error("INFORME UM CPF VÁLIDO.");if(senha.length<6)throw new Error("A SENHA PRECISA TER AO MENOS 6 CARACTERES.");const cred=await createUserWithEmailAndPassword(auth,`${usuario}@${loginDomain}`,senha);await set(ref(db,`users/${cred.user.uid}`),{username:usuario,fullName:nome,phone:telefone,cpf,createdAt:serverTimestamp()});usuarioAtual=cred.user;perfilAtual={username:usuario,fullName:nome,phone:telefone};$("#form-cadastro").reset();exibirBebidas();}catch(err){erroCadastro.textContent=mensagemErro(err);}});
$("#lista-bebidas").addEventListener("click",e=>{const m=e.target.closest("[data-minus]"),p=e.target.closest("[data-plus]"),b=e.target.closest(".produto");if(m){e.stopPropagation();remover(m.dataset.minus);}else if(p){e.stopPropagation();adicionar(p.dataset.plus);}else if(b)adicionar(b.dataset.bebida);});botaoCarrinho.addEventListener("click",abrirCarrinho);$("#fechar-carrinho").addEventListener("click",fecharCarrinho);$("#limpar-carrinho").addEventListener("click",()=>{carrinho={};atualizarInterface();atualizarCarrinho();});listaCarrinho.addEventListener("click",e=>{const m=e.target.closest("[data-cart-minus]"),p=e.target.closest("[data-cart-plus]"),r=e.target.closest("[data-remove]");if(m)remover(m.dataset.cartMinus);if(p)adicionar(p.dataset.cartPlus);if(r)excluir(r.dataset.remove);});
$("#confirmar-carrinho").addEventListener("click",async()=>{if(!usuarioAtual||!totalItens())return;const b=$("#confirmar-carrinho");b.disabled=true;try{if(!demoLocal){const items=Object.entries(carrinho).map(([drink,quantity])=>({drink,quantity}));const pedido=push(ref(db,"orders"));await registrarPedidoNaPlanilha(pedido.key,items);await set(pedido,{uid:usuarioAtual.uid,username:perfilAtual.username,fullName:perfilAtual.fullName,items,totalItems:totalItens(),status:"pending",createdAt:serverTimestamp()});}fecharCarrinho();mostrarObrigado();}catch(err){alert(mensagemErro(err));b.disabled=false;}});$("#botao-sair").addEventListener("click",retornarAoLogin);
const fecharObrigado=document.createElement("button");fecharObrigado.id="fechar-obrigado";fecharObrigado.type="button";fecharObrigado.setAttribute("aria-label","FECHAR");fecharObrigado.textContent="×";obrigado.prepend(fecharObrigado);fecharObrigado.addEventListener("click",retornarAoLogin);
const tema=$("#botao-tema"),icone=$("#icone-tema");function aplicarTema(t){document.documentElement.classList.toggle("dark",t==="dark");icone.innerHTML=t==="dark"?`<path d="M21 12.8A8.5 8.5 0 1 1 11.2 3A6.7 6.7 0 0 0 21 12.8Z"/>`:`<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41"/>`;}aplicarTema(localStorage.getItem("clube14bis-tema")==="dark"?"dark":"light");tema.addEventListener("click",()=>{const t=document.documentElement.classList.contains("dark")?"light":"dark";aplicarTema(t);localStorage.setItem("clube14bis-tema",t);});
aplicarTema("light");
try{if(!firebaseConfig?.apiKey||!firebaseConfig?.databaseURL)throw new Error("CONFIGURE O FIREBASE.");app=initializeApp(firebaseConfig);auth=getAuth(app);db=getDatabase(app);}catch(e){if(!demoLocal)erroLogin.textContent=e.message;}
